### ISSUE TITLE
missing html folder

### ISSUE THREAD

**Issue by techaround** [Patrick-Hogan/wandering_inn#1]
Running ubuntu 20.04. 

It would not work until I created a folder called html in the_wandering_inn folder.

**Comment by NRizzoInc** [comment]
The html directory is also missing the title page. Based on examples provided by the ebookmaker lib, the title page (located at `wandering_inn/the_wandering_inn/html/title.html`) should look like this:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:lang="en" >
<head>
<title>The Wandering Inn</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" href="style.css" type="text/css" />
</head>
<body>

<h1>The Wandering Inn</h1>

<p style="height: 20px;">&nbsp;</p>

<h3>Pirate Aba</h3>

</body>
</html>
```

**Comment by Patrick-Hogan** [comment]
Thanks for the feedback. I added commands to check for and, if necessary, create all required directories. 

For title.html: This file is now automatically generated during the ebook creation process (never shows up in the html directory, but is visible if you unzip the epub; this was a bug previously, fixed along with other bugfixes I just pushed up).
