### ISSUE TITLE
2 possible problems

### ISSUE THREAD

**Issue by heromatic** [Patrick-Hogan/wandering_inn#10]
Hi there,
I never used github before so I dont know if I am doing any of this correctly... 
I found this project a couple of days ago. 
I am a beginner programmer and I tried creating something similar to this with selenium before. 
I found one Problem with your implementation. In some chapters "Author Notes" where not declared as such, thats why sometimes your implementation would include the pictures and non chapter information postet by pirateaba. I think I found a fix for that. Please note I am a beginner so function can propably written ALOT better. But it was the best I could do. Currently the code would start at line 71 of your code.

```
        author_note = [p for p in contents.find_all('p') if p.getText()[0:6] == 'Author' and 'Note' in p.getText()[0:13]]
        if author_note:
            end_content = author_note[0]
            [s.decompose() for s in end_content.find_next_siblings()]
            end_content.decompose()
        else:
            # added a way to find and handle the rare cases, where Auther Note: was not used in the end of a chapter to designate the community additions
            old_index = False
            count = 0
            for index, a in enumerate(reversed(list(contents.find_all('p')))):
                if index >= 60: #is just a guess that seemed to work, anything higher then 60 lines is VERY unlikely to still be a Authors Note
                    break
                if a.contents == ['\xa0']:
                    if not old_index:
                        old_index = index
                    if (index - old_index) == 1:
                        count += 1
                    else:
                        count = 0
                    old_index = index
                    if count == 3:
                        [s.decompose() for s in a.find_next_siblings()]
                        break

```
I also wrote a second function to work with the colorcodes that you find in your strip_color function. This adds the colorname as Stringtext in the beginning and end of the found tag containing the color. That way you would still know if a text was colorcoded in a ebook reader. it would need the webcolors library from pypi, so I dont know if this is anything too interesting for you... 
It would in the end look like this: |GOLD| Nevermore |GOLD|
The code I wrote is:
```
import webcolors
import re

def closest_colour(requested_colour):
    """finds the closest color that returns a name from Webcolors"""
    min_colours = {}
    for key, name in webcolors.CSS2_HEX_TO_NAMES.items():
        r_c, g_c, b_c = webcolors.hex_to_rgb(key)
        rd = (r_c - requested_colour[0]) ** 2
        gd = (g_c - requested_colour[1]) ** 2
        bd = (b_c - requested_colour[2]) ** 2
        min_colours[(rd + gd + bd)] = name
    return min_colours[min(min_colours.keys())]

def get_colour_name(requested_colour):
    """Checks if the name of a color can be found by the RGB color code.
    If it can't be found it uses the closest_colour method to return the most likely candidate for a colorname."""
    try:
        closest_name = webcolors.rgb_to_name(requested_colour)
    except ValueError:
        closest_name = closest_colour(requested_colour)
    return " |" + closest_name.upper()+ "| "

```

and then at the strip_color check:

```
        if strip_color:
            # Strip color from text that can make it hard to read on a paperwhite:
            for span in contents.find_all('span'):
                if 'color' in str(span):
                    # added a way to find the name of the found color and add them to the tag, it can then be used in black and white kindle devices to see what text was originaly color coded
                    color = re.findall(r'(?<=color\:\#).{6}', str(span))[0]
                    color = (int(color[0:2], 16), int(color[2:4], 16), int(color[4:6], 16))
                    color = get_colour_name(color)
                    span.insert(0, color)
                    span.append(color)
                    span.unwrap() # bs4 method for replaceWithChildren
```

I know that non of this is an issue but I didn't really understand how any of this push and pull request stuff works or if there is a better way to send someone a messege on here. I hope any of this is usefull in some way.

**Comment by Patrick-Hogan** [comment]
Apologies for taking so long to get back to you--I was on vacation shortly after you posted this and forgot about it by the time I got back. 

I really liked and implemented a version of your color suggestion. Generally speaking, PR just means you fork (create a copy of the repo), make your changes locally, push to your fork and submit a request that I merge your work into this repo; for something major, that makes it a lot easier than copying code snippets, but for something this small that I wanted to do some rewriting anyways, it's not a big deal either way. 

I didn't merge in the changes for authors notes; i've considered doing something like that before, but I'm leery of accidentally missing content on some future story when pirate skips labeling and happens to format the end of the page in a weird way. For me at least, I find some extra cruft in the ebook to be a small price to pay for ensuring all content is present--I'd rather include too much than too little. I make take another look and review the pros and cons in the future, but I'm leaving that part untouched for now. 

Thanks for the comments!
