### ISSUE TITLE
Wordpress Rate Limiter

### ISSUE THREAD

**Issue by Patrick-Hogan** [Patrick-Hogan/wandering_inn#15]
Using this project on a large number of  chapters causes the user's IP address to be banned by wanderinginn.com with the following error:

```

WordPress Backup & Security Plugin - BlogVault Firewall

Blocked because of Malicious Activities

Reference ID: <removed>

```

Presumably, the script hits some rate limit that trips a ban. Running for a few chapters at a time seems okay for now. 

Workarounds: 

- Only use the script to download individual chapters at once
- (potential) Update the script to limit the rate at which wanderinginn.com is queried (this will result in significantly longer run times, but may prevent the ban). Make heavier and more organized caching of pages to make the delay less of  a problem.

**Comment by JJTech0130** [comment]
I contacted TWI WebDev on Discord, and they were happy to whitelist me once I explained my situation. Not sure if it actually will prevent be from being banned again (not trying), but at least my main IP is now unbanned.

**Comment by Patrick-Hogan** [comment]
Added a rate limiter to limit calls to once a minute and still got banned before downloading a single chapter. I think I'll have to reach out on discord as well when I get time.
