### ISSUE TITLE
Had to add clone/submodule specific ebookmaker version

### ISSUE THREAD

**Issue by NRizzoInc** [Patrick-Hogan/wandering_inn#2]
I could not simply `python -m pip install ebookmaker`. I had to add the [linked ebookmaker](https://github.com/setanta/ebookmaker) in the readme as a submodule relative to the root of this repo.

**Comment by Patrick-Hogan** [comment]
Thanks for the feedback--I added it as a submodule here as well to make setup easier for new users.
