### ISSUE TITLE
Tool no longer works with the redesign

### ISSUE THREAD

**Issue by Shadow-Master** [Patrick-Hogan/wandering_inn#20]
When trying after the redesign, on a new IP that is not banned, I get the following result when running the script:

```sh
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2188]
└─[$] python3 wanderinginn2epub.py                                                                    [8:51:27]
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn".
ePub file "./build/The Wandering Inn.epub" successfully generated.
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2189]
└─[$] cat cmd                                                                                         [8:51:38]
python3 wanderinginn2epub.py --volume 1 2 3 4 5 6 7 8 9 --output-by-volume
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2190]
└─[$] $(cat cmd)                                                                                      [8:53:22]
Chapter: 0it [00:00, ?it/s]                                                               | 0/9 [00:00<?, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 1".
ePub file "./build/The Wandering Inn - Volume 1.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 2".
ePub file "./build/The Wandering Inn - Volume 2.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]█▎                                                     | 2/9 [00:00<00:00, 10.64it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 3".
ePub file "./build/The Wandering Inn - Volume 3.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 4".
ePub file "./build/The Wandering Inn - Volume 4.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]████████████████▋                                      | 4/9 [00:00<00:00, 10.73it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 5".
ePub file "./build/The Wandering Inn - Volume 5.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 6".
ePub file "./build/The Wandering Inn - Volume 6.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]████████████████████████████████                       | 6/9 [00:00<00:00, 10.67it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 7".
ePub file "./build/The Wandering Inn - Volume 7.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 8".
ePub file "./build/The Wandering Inn - Volume 8.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]███████████████████████████████████████████████▎       | 8/9 [00:00<00:00, 10.74it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 9".
ePub file "./build/The Wandering Inn - Volume 9.epub" successfully generated.
Volume: 100%|█████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 10.74it/s]



```

The ebooks are empty and do not contain any info, even when doing it by volume. I assume there is some issue finding the content or URLs. I have confirmed that I can hit the site, and other scraper can see content.

What logs can I give you to help you fix?

**Comment by JJTech0130** [comment]
Try applying my PR: https://github.com/Patrick-Hogan/wandering_inn/pull/21
If you want to debug this in the future, use the flag `--output-print-index`, that way you know what chapters are actually being extracted from the TOC.

**Comment by Shadow-Master** [comment]
Hey, thanks!

I am IP banned from the site and using a proxy to reach out. I have noticed that it 404's on many images trying to download, when they work fine on the browser. I have added the following lines of code to make a workaround, but I was curious why it happens in the script, given the browser works fine with the images...

lines 125-129 now:
```python
                    try:
                        fo.write(urlopen(img['src'].split("?")[0], timeout=5).read())
                        img['src'] = os.path.join(image_path, img_filename)
                    except:
                        print(f'Removing image: unable to determine filename:\n\t{img}')
```

And then after a huge amount of debugging, I have added the following lines in ebookmaker.py, lines 244-249
```py
        for image in self.images:
            try:
                imageFile = os.path.join('OEBPS', image)
                epubFile.write(image, imageFile)
            except FileNotFoundError:
                continue
```

And now it is generated. I wish I knew why the files aren't fetched correctly though...

**Comment by JJTech0130** [comment]
No idea, to be honest I don't care about the images because I'm reading it on a Kindle which can't display them anyway...
What chapters are they in? I don't see any errors about images myself.

**Comment by Shadow-Master** [comment]
They usually come at the end of every chapter. I am not bothered by them not being there, I just wanted epub generation which works when I add the try/catch. The issue is, it 404's or times out with script while working fine with the browser and I didn't understand why. Maybe a headless chrome would be able to download the files correctly? Why would a standard request fail?

**Comment by JJTech0130** [comment]
I mean, I'm downloading by chapter and don't seem to be affected. I'll try it on a droplet or something later so I don't get my IP banned.

**Comment by Shadow-Master** [comment]
ok let me know if `python3 wanderinginn2epub.py --output-title "The Wandering Inn - Colored"` generates an epub without errors for you please. If it does, can I have the full 9 volume epub you create please? My code is just constantly borked. Maybe it's a side affect of using PIA as my VPN and not an AWS VPS or DO droplet. I wonder if I can get a different result from one of those.

**Comment by JJTech0130** [comment]
Ok, I came up with a minimum reproduction of the bug:
```python3
from urllib.request import urlopen
urlopen("https://i0.wp.com/wanderinginn.com/wp-content/uploads/2023/03/Amentus_Archival.png?resize=2397%2C3455&ssl=1").read()
```
Interestingly, if I replace it with
```python3
import requests
requests.get("https://i0.wp.com/wanderinginn.com/wp-content/uploads/2023/03/Amentus_Archival.png?resize=2397%2C3455&ssl=1")
```
it works fine. So, a simple fix for now would be to do just that. I am curious what urllib is doing differently, considering that `requests` uses it under the hood. I will mitm it in a minute.

**Comment by JJTech0130** [comment]
Wait a second, the request works fine on my main device, even with urllib? It only fails on the droplet?!
EDIT: Wait, it seems to be python version dependent? That's why I didn't notice it before, I was running with python 3.11. If I use a python 3.9 installation, it breaks as described. The droplet has python 3.9.

**Comment by JJTech0130** [comment]
This is the weirdest bug ever. It seem to be some weird issue with urllib on python3.9?
This will trigger it:
```python3
from urllib.request import urlopen
urlopen("https://i0.wp.com/wanderinginn.com/wp-content/uploads/2023/03/Amentus_Archival.png?resize=2397%2C3455&ssl=1").read()
```
but this will not:
```python3
from urllib.request import urlopen
import ssl
urlopen("https://i0.wp.com/wanderinginn.com/wp-content/uploads/2023/03/Amentus_Archival.png?resize=2397%2C3455&ssl=1", context=ssl.create_default_context()).read()
```

**Comment by JJTech0130** [comment]
Maybe it's not a bug in urllib, and wanderinginn's image host is using TLS fingerprinting? Not sure why urllib in 3.9 isn't using the default context, but adding that fixes it so that might be the simplest solution. TBH I would recommend switching to requests since the API is nicer, but whatever. I'll make a PR.

EDIT:
https://github.com/Patrick-Hogan/wandering_inn/pull/22 should hopefully work?

**Comment by JJTech0130** [comment]
(if you want to try them both at once, https://github.com/JJTech0130/wandering_inn/tree/test has both fixes)

**Comment by Shadow-Master** [comment]
Tried from your commit:
```bash
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2278]
└─[$] python3 --version                                                                              [11:47:45]
Python 3.8.10
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2279]
└─[$] python3 wanderinginn2epub.py --output-title "The Wandering Inn - Colored"                      [11:47:47]
Volume: 1
Volume: 2
Volume: 3
Volume: 4
Volume: 5
Volume: 6
Volume: 7
Volume: 8
Volume: 9
Chapter:   0%|▏                                                                 | 2/657 [00:09<51:24,  4.71s/it]
Traceback (most recent call last):
  File "wanderinginn2epub.py", line 386, in <module>
    main()
  File "wanderinginn2epub.py", line 376, in main
    get_book(ebook_data,
  File "wanderinginn2epub.py", line 311, in get_book
    raise err
  File "wanderinginn2epub.py", line 308, in get_book
    ch.save(stream=fh, strip_color=strip_color, image_path=image_path)
  File "wanderinginn2epub.py", line 125, in save
    fo.write(urlopen(img['src'], timeout=5).read())
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by JJTech0130** [comment]
Hrm… maybe try switching it out for requests then… I will see if I can get 3.8 installed to test. Or you could try with 3.9 or 3.11

**Comment by Shadow-Master** [comment]
Wait, I changed some network settings and removed some upstream stuff and its (slowly) working. I will let it do it's thing and browse to see if pics are created. I will try to update python but its a WSL ubuntu VM, and currently not in the repos :( 

Edit: I will just use Microsoft Stores and install 3.11 over my 3.10 it timed out on the read op with 3.8 with the new repo.
Edit Pillow doesn't play nicely with windows...

If you do do an update to switch it out to requests, please let me know, and I will clone from whatever branch or main repo it is and try it then.

**Comment by Shadow-Master** [comment]
Ok, here we go.

> Hrm… maybe try switching it out for requests then… I will see if I can get 3.8 installed to test. Or you could try with 3.9 or 3.11

```bash
└─[$] python3 --version                                                                              [14:22:35]
Python 3.10.6
```

I installed WSL2 Ubuntu 22.04. At this point I am in so deep, it's not even a joke. That version of ubuntu has Python 3.10 in the repos, and 3.11 as well, but no PIP for 3.11 and I cannot be bothered to get it working. Upon using your test branch with 3.10, it works. It downloads things straight. It timed out once, but the cache is there upon reruns and picks up right away without issues. Then we hit the following snag.

```bash
└─[$] python3 wanderinginn2epub.py --output-title "The Wandering Inn - Colored"                      [14:20:43]
Volume: 1
Volume: 2
Volume: 3
Volume: 4
Volume: 5
Volume: 6
Volume: 7
Volume: 8
Volume: 9
Chapter: 100%|████████████████████████████████████████████████████████████████| 657/657 [00:58<00:00, 11.21it/s]
/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py:65: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 65 of the file /home/switchblade/wandering_inn/ebookmaker/ebookmaker.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(f.read())
Traceback (most recent call last):
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 387, in <module>
    main()
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 383, in main
    gen = OPFGenerator(ebook_data)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 105, in __init__
    Generator.__init__(self, ebookData)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 54, in __init__
    self.outline[fname] = self.outlineEBookContents(fname, depth)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 67, in outlineEBookContents
    outline = [h for h in soup.body if getattr(h, 'name', None) in hTags and int(h.name[-1]) <= depth]
TypeError: 'NoneType' object is not iterable
```

Not sure why there would be a missing check there that was not an issue in the past, but I don't know exactly what changes were made for this to appear. In any case, the content gets downloaded, but the epub is not generated. Thoughts?

**Comment by JJTech0130** [comment]
My guess is that a specific chapter is causing it? Could you try for example just 1.00 as a sanity check? (I only download specific chapters myself in order to avoid being banned)

**Comment by Shadow-Master** [comment]
Your intuition is correct, all volumes but 9 work perfectly. My guess is that the final chapter with no content is causing it. Worth having the script ignore the last chapter of the ToC? Or somehow filtering out the password protected chapter?

**Comment by JJTech0130** [comment]
Interesting, the password protected chapter seemed to work for me...? Maybe try that specifically. Could also write something to print out what chapter it is processing when it crashes

**Comment by Shadow-Master** [comment]
Sorry, can you explain what you want me to do further? I am not clear what you mean.

Ok, so I added a line to remove the patreon chapter in the get_index function simply doing `index.pop()`

The chapter is not noted in the printed index, but the script still crashes. Which means that it's not that chapter. I will go through them one by one, and see which is it, except for interludes.

Do you happen to know how to clear the cache of the script or force a specific chapter update?

**Comment by JJTech0130** [comment]
I figured out which chapter is causing it, it's 9.03 (I just went to the crashing line in ebookmaker and added
```py
print("HTML FILE: ", htmlFile)
```
above it)

**Comment by Shadow-Master** [comment]
It varies, I think. Why is it causing it for you? I get a new interesting error. Do you happen to know how to clear the cache of the script or force a specific chapter update?

```bash
python3 wanderinginn2epub.py --output-title "test" --chapter 9.00 9.01 9.02 9.03 9.04 9.05 9.06 9.07 9.08
9.09 9.10
Volume: 1
Volume: 2
Volume: 3
Volume: 4
Volume: 5
Volume: 6
Volume: 7
Volume: 8
Volume: 9
Unable to find matching chapter for 9.05: list index out of range
Unable to find matching chapter for 9.09: list index out of range
Unable to find matching chapter for 9.10: list index out of range
Chapter: 100%|████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 166111.05it/s]
/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py:65: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 65 of the file /home/switchblade/wandering_inn/ebookmaker/ebookmaker.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(f.read())
Traceback (most recent call last):
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 387, in <module>
    main()
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 383, in main
    gen = OPFGenerator(ebook_data)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 105, in __init__
    Generator.__init__(self, ebookData)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 54, in __init__
    self.outline[fname] = self.outlineEBookContents(fname, depth)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 67, in outlineEBookContents
    outline = [h for h in soup.body if getattr(h, 'name', None) in hTags and int(h.name[-1]) <= depth]
TypeError: 'NoneType' object is not iterable
```

**Comment by JJTech0130** [comment]
I think the problem with 9.05 etc. is just because they have a letter after their name (the chapter title is actually "9.05 NPR", make sure you have the quotes)
(also lol just realized I forgot to remove the Volume: prints in my pr, that's why it prints them all for you lol)

To clear the cache, you can just remove the entire build folder, btw

**Comment by Shadow-Master** [comment]
Yeah I see 9.03 is empty in my cache files in the HTML. I will delete it and try to redownload.

**Comment by JJTech0130** [comment]
It's empty in mine too, think there might be a bug downloading it?

**Comment by Shadow-Master** [comment]
Yeah, the chapter has a weird image that 404's right in the beginning. I increased the timeout to 10 and now the request 400's for me. I will post logs.

```bash
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2357]
└─[$] python3 wanderinginn2epub.py --output-title "test" --chapter 9.00 9.01 9.02 9.03               [15:49:38]
Volume: 1
Volume: 2
Volume: 3
Volume: 4
Volume: 5
Volume: 6
Volume: 7
Volume: 8
Volume: 9
Chapter: 100%|████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 101067.57it/s]
/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py:65: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 65 of the file /home/switchblade/wandering_inn/ebookmaker/ebookmaker.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(f.read())
Traceback (most recent call last):
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 386, in <module>
    main()
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 382, in main
    gen = OPFGenerator(ebook_data)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 105, in __init__
    Generator.__init__(self, ebookData)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 54, in __init__
    self.outline[fname] = self.outlineEBookContents(fname, depth)
  File "/home/switchblade/wandering_inn/ebookmaker/ebookmaker.py", line 67, in outlineEBookContents
    outline = [h for h in soup.body if getattr(h, 'name', None) in hTags and int(h.name[-1]) <= depth]
TypeError: 'NoneType' object is not iterable
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2357]
└─[$] python3 wanderinginn2epub.py --output-title "test" --chapter 9.00 9.01 9.02 9.03               [15:51:00]
Volume: 1
Volume: 2
Volume: 3
Volume: 4
Volume: 5
Volume: 6
Volume: 7
Volume: 8
Volume: 9
Chapter:  75%|███████████████████████████████████████████████████                 | 3/4 [00:03<00:01,  1.21s/it]
Traceback (most recent call last):
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 386, in <module>
    main()
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 376, in main
    get_book(ebook_data,
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 311, in get_book
    raise err
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 308, in get_book
    ch.save(stream=fh, strip_color=strip_color, image_path=image_path)
  File "/home/switchblade/wandering_inn/wanderinginn2epub.py", line 126, in save
    fo.write(urlopen(img['src'], timeout=10, context=ssl.create_default_context()).read())
...snip...
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by JJTech0130** [comment]
I think the image might just be bad, I replaced the image downloading part with something that just removes all images entirely and it's fine after that.

**Comment by Shadow-Master** [comment]
RIP, I liked the images and we got so far, with only a single chapter causing us issues at this point. No workarounds other than removing images entirely?

What about a try/catch block there?

**Comment by JJTech0130** [comment]
Oh sure, I could do that. I just meant that it's definitely the image, because removing it fixes it. I will implement something proper and PR it. I also mentioned in the Discord that the image is broken.

**Comment by Shadow-Master** [comment]
I am trying with a try/catch right now. I will wait for your pull, because your code is undoubtedly better than mine.

**Comment by JJTech0130** [comment]
I also want to add a flag to *not* download images, because it's time consuming and my e-reader doesn't display them anyway.

**Comment by Shadow-Master** [comment]
That makes sense. A try/Except block does indeed download the chapter, *but* the image causes it to crash on creating the epub. I am working on it. Current changes are simply in the main file, lines 124 on to be replaced with 
```py
            if img_filename:
                try:
                    with open(os.path.join(image_path, img_filename), 'wb') as fo:
                        fo.write(urlopen(img['src'], timeout=5, context=ssl.create_default_context()).read())
                    img['src'] = os.path.join(image_path, img_filename)
                except:
                    continue
```

and in ebookmaker.py, line 246:
```py
        for image in self.images:
            imageFile = os.path.join('OEBPS', image)
            try:
                epubFile.write(image, imageFile)
            except FileNotFoundError:
                print("Image not found!")
                continue
```

**Comment by Shadow-Master** [comment]
THAT WORKED!! Volume 9 is output correctly, without that image!
Weirdly enough, my UK VPS displays that image. No idea. The point is, by volume, and all volume output with pictures now works. The SSL errors on most of the images, and the weird case of 404ing images was solved and the tool works. Doubtless your pull will be better, but the two try/except blocks were helpful.

**Comment by Shadow-Master** [comment]
@JJTech0130 It's borked again :( likely a contents page update. Not sure...

**Comment by Shadow-Master** [comment]
@JJTech0130 Fixed. The new code is:
Lines 227-236
```python
for div in toc.find_all('div', recursive=True):
        if 'volume-wrapper' in div['class']:
            volume = int(div.find('h2').text.replace("Volume", "").strip())
            print(f'Volume: {volume}')
        elif 'book-body' in div['class']:
            print(div['class'])
            for chapter in div.find_all('div', {'class': 'chapter-entry'}):
                link = chapter.find('a', href=True)
                index.append(Chapter(link['href'], link.text, volume, len(index)))  
    return index
```

**Comment by JJTech0130** [comment]
At this point I’m just going to leave it alone until it stabilizes

**Comment by Shadow-Master** [comment]
Fair enough. Since I am not sure when that will be, I am going to keep making micro patches and documenting them here.
