### ISSUE TITLE
Unable to get volume from text

### ISSUE THREAD

**Issue by brho** [Patrick-Hogan/wandering_inn#25]
```
$ ./wanderinginn2epub.py --output-print-index
Unable to get volume from text: <p class="announcement-lowkey-item-category responsive-small"></p>
```

Perhaps the table-of-contents/ page was changed?

**Comment by Tentoe** [comment]
#23 works for me
clone his fork and `git checkout fix-index-scrapping-jul-2023`

edit: there still is a bug with indexing the chapters

**Comment by Patrick-Hogan** [comment]
This should be fixed in the latest round of merges.
