### ISSUE TITLE
 from ebookmaker.EbookMaker import OPFGenerator ImportError: cannot import name 'OPFGenerator' from 'ebookmaker.EbookMaker'

### ISSUE THREAD

**Issue by notasprint** [Patrick-Hogan/wandering_inn#9]
Hi, I am incredibly new to any of this and I was met with these two lines. is there a fix or quick solution? thanks

**Comment by Patrick-Hogan** [comment]
Did you include `--recurse-submodules` in your clone command (or run `git submodule init; git submodule update` after cloning, or clone https://github.com/setanta/ebookmaker into this project)? 

Sounds like you're missing the ebookmaker dependency (which is *not* currently the ebookmaker package installable by pip; you need to use the submodule or manually clone the link in this response into the wandering_inn folder).
